# Generated by Django 3.1.7 on 2022-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('two_letter_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata_code', models.CharField(max_length=3)),
                ('iso_alpha_3_code', models.CharField(max_length=3)),
                ('long_name', models.CharField(max_length=50)),
                ('long_location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=3)),
                ('arrival', models.CharField(max_length=3)),
                ('terminal', models.CharField(max_length=2)),
                ('aircraft', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('crew', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=20)),
                ('family_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('dob', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=20)),
                ('passport_number', models.CharField(max_length=50)),
                ('country_of_issue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrorism', models.DecimalField(decimal_places=2, max_digits=3)),
                ('narcotics', models.DecimalField(decimal_places=2, max_digits=3)),
                ('smuggling', models.DecimalField(decimal_places=2, max_digits=3)),
                ('illegal_immigration', models.DecimalField(decimal_places=2, max_digits=3)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
