# Generated by Django 3.1.7 on 2022-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0002_auto_20220403_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
