# Generated by Django 3.1.7 on 2022-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts', '0003_auto_20220403_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerrisk',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
